[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-inject"
version = "0.1.0"
classifiers = [
    "Framework :: Pytest",
]
dependencies = [
    "pytest>=6.0.0",
]

[project.entry-points.pytest11]
pytest_inject = "pytest_inject.plugin"